import React from 'react';
import { Document, Page, View, Text, StyleSheet } from '@react-pdf/renderer';
import { fonts, fontSizes, colors, spacing, pageDimensions } from './fonts';

// Base styles used across all templates
export const baseStyles = StyleSheet.create({
  page: {
    fontFamily: fonts.primary,
    fontSize: fontSizes.body,
    color: colors.black,
    backgroundColor: colors.white,
    padding: pageDimensions.margin,
    paddingBottom: pageDimensions.margin + 20, // Extra space for footer
  },
  
  // Header section
  header: {
    marginBottom: spacing.lg,
    borderBottomWidth: 2,
    borderBottomColor: colors.lightGray,
    paddingBottom: spacing.md,
  },
  
  title: {
    fontFamily: 'Helvetica-Bold',
    fontSize: fontSizes.title,
    color: colors.black,
    marginBottom: spacing.sm,
  },
  
  subtitle: {
    fontFamily: fonts.primary,
    fontSize: fontSizes.body,
    color: colors.darkGray,
  },
  
  // Name/Date line
  nameDate: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: spacing.md,
    gap: spacing.lg,
  },
  
  nameDateField: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: spacing.xs,
  },
  
  nameDateLabel: {
    fontSize: fontSizes.body,
    fontFamily: 'Helvetica-Bold',
  },
  
  nameDateLine: {
    flex: 1,
    borderBottomWidth: 1,
    borderBottomColor: colors.black,
    minWidth: 100,
  },
  
  // Instructions
  instructions: {
    marginBottom: spacing.lg,
    padding: spacing.md,
    backgroundColor: colors.veryLightGray,
    borderRadius: 4,
  },
  
  instructionsText: {
    fontSize: fontSizes.body,
    fontStyle: 'italic',
    color: colors.darkGray,
  },
  
  // Content area
  content: {
    flex: 1,
  },
  
  // Footer
  footer: {
    position: 'absolute',
    bottom: spacing.lg,
    left: pageDimensions.margin,
    right: pageDimensions.margin,
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: colors.lightGray,
    paddingTop: spacing.sm,
  },
  
  footerText: {
    fontSize: fontSizes.tiny,
    color: colors.mediumGray,
  },
  
  pageNumber: {
    fontSize: fontSizes.tiny,
    color: colors.mediumGray,
  },
  
  // Word bank
  wordBank: {
    marginBottom: spacing.lg,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.lightGray,
    borderRadius: 4,
  },
  
  wordBankTitle: {
    fontSize: fontSizes.small,
    fontFamily: 'Helvetica-Bold',
    marginBottom: spacing.sm,
    color: colors.darkGray,
  },
  
  wordBankWords: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  
  wordBankWord: {
    fontSize: fontSizes.body,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    backgroundColor: colors.veryLightGray,
    borderRadius: 4,
  },
});

// Header component with title, name, and date fields
interface HeaderProps {
  title: string;
  subtitle?: string;
  showNameDate?: boolean;
}

export const Header: React.FC<HeaderProps> = ({ 
  title, 
  subtitle, 
  showNameDate = true 
}) => (
  <View style={baseStyles.header}>
    <Text style={baseStyles.title}>{title}</Text>
    {subtitle && <Text style={baseStyles.subtitle}>{subtitle}</Text>}
    {showNameDate && (
      <View style={baseStyles.nameDate}>
        <View style={baseStyles.nameDateField}>
          <Text style={baseStyles.nameDateLabel}>Name:</Text>
          <View style={baseStyles.nameDateLine} />
        </View>
        <View style={baseStyles.nameDateField}>
          <Text style={baseStyles.nameDateLabel}>Date:</Text>
          <View style={baseStyles.nameDateLine} />
        </View>
      </View>
    )}
  </View>
);

// Instructions component
interface InstructionsProps {
  text: string;
}

export const Instructions: React.FC<InstructionsProps> = ({ text }) => (
  <View style={baseStyles.instructions}>
    <Text style={baseStyles.instructionsText}>{text}</Text>
  </View>
);

// Footer component with attribution and page number
interface FooterProps {
  attribution?: string;
  showPageNumber?: boolean;
}

export const Footer: React.FC<FooterProps> = ({ 
  attribution = 'Generated by Worksheet Generator',
  showPageNumber = true,
}) => (
  <View style={baseStyles.footer} fixed>
    <Text style={baseStyles.footerText}>{attribution}</Text>
    {showPageNumber && (
      <Text 
        style={baseStyles.pageNumber}
        render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`}
      />
    )}
  </View>
);

// Word bank component
interface WordBankProps {
  words: string[];
  title?: string;
}

export const WordBank: React.FC<WordBankProps> = ({ 
  words, 
  title = 'Word Bank' 
}) => (
  <View style={baseStyles.wordBank}>
    <Text style={baseStyles.wordBankTitle}>{title}</Text>
    <View style={baseStyles.wordBankWords}>
      {words.map((word, index) => (
        <Text key={index} style={baseStyles.wordBankWord}>
          {word}
        </Text>
      ))}
    </View>
  </View>
);

// Base worksheet document wrapper
interface WorksheetDocumentProps {
  children: React.ReactNode;
  title?: string;
}

export const WorksheetDocument: React.FC<WorksheetDocumentProps> = ({ 
  children,
  title = 'Worksheet',
}) => (
  <Document title={title} author="Worksheet Generator">
    {children}
  </Document>
);

// Base page wrapper
interface WorksheetPageProps {
  children: React.ReactNode;
  showFooter?: boolean;
}

export const WorksheetPage: React.FC<WorksheetPageProps> = ({ 
  children,
  showFooter = true,
}) => (
  <Page size="LETTER" style={baseStyles.page}>
    <View style={baseStyles.content}>
      {children}
    </View>
    {showFooter && <Footer />}
  </Page>
);
