// Header and Footer Configuration Types
// These allow teachers/users to customize worksheet branding

/**
 * Header configuration for worksheets
 */
export interface HeaderConfig {
  // Branding
  logoUrl?: string;           // URL to uploaded logo image
  schoolName?: string;        // e.g., "Lincoln Elementary School"
  
  // Class info
  className?: string;         // e.g., "3rd Grade Science"
  teacherName?: string;       // e.g., "Mrs. Johnson"
  period?: string;            // e.g., "Period 2" or "Block A"
  
  // Student fields (show blank lines for student to fill in)
  showNameField?: boolean;    // Default: true
  showDateField?: boolean;    // Default: true
  showScoreField?: boolean;   // Default: false
  showPeriodField?: boolean;  // Default: false
  
  // Display options
  style?: 'standard' | 'compact' | 'minimal';  // Layout style
  accentColor?: string;       // Color for borders/accents (hex)
  
  // Custom text
  customSubtitle?: string;    // Custom text below title
}

/**
 * Footer configuration for worksheets
 */
export interface FooterConfig {
  // Attribution
  attribution?: string;       // Default: "Generated by Worksheet Generator"
  showAttribution?: boolean;  // Default: true
  
  // Copyright/branding
  copyrightText?: string;     // e.g., "© 2026 Lincoln Elementary"
  schoolWebsite?: string;     // e.g., "www.lincolnelementary.org"
  
  // Page numbers
  showPageNumbers?: boolean;  // Default: true
  pageNumberFormat?: 'simple' | 'full';  // "1" vs "Page 1 of 3"
  
  // Logo (small version)
  logoUrl?: string;           // Small logo in footer
  
  // Style
  style?: 'standard' | 'minimal' | 'none';
}

/**
 * Combined worksheet customization options
 */
export interface WorksheetBranding {
  header?: HeaderConfig;
  footer?: FooterConfig;
}

/**
 * Default header configuration
 */
export const defaultHeaderConfig: HeaderConfig = {
  showNameField: true,
  showDateField: true,
  showScoreField: false,
  showPeriodField: false,
  style: 'standard',
};

/**
 * Default footer configuration
 */
export const defaultFooterConfig: FooterConfig = {
  attribution: 'Generated by Worksheet Generator',
  showAttribution: true,
  showPageNumbers: true,
  pageNumberFormat: 'full',
  style: 'standard',
};

/**
 * Merge user config with defaults
 */
export function mergeHeaderConfig(config?: Partial<HeaderConfig>): HeaderConfig {
  return { ...defaultHeaderConfig, ...config };
}

export function mergeFooterConfig(config?: Partial<FooterConfig>): FooterConfig {
  return { ...defaultFooterConfig, ...config };
}

/**
 * Example preset configurations for common use cases
 */
export const presets = {
  // Simple worksheet for homeschool
  homeschool: {
    header: {
      showNameField: true,
      showDateField: true,
      showScoreField: false,
      style: 'minimal' as const,
    },
    footer: {
      showAttribution: false,
      showPageNumbers: true,
      pageNumberFormat: 'simple' as const,
      style: 'minimal' as const,
    },
  },
  
  // Full classroom worksheet
  classroom: {
    header: {
      showNameField: true,
      showDateField: true,
      showScoreField: true,
      showPeriodField: true,
      style: 'standard' as const,
    },
    footer: {
      showAttribution: true,
      showPageNumbers: true,
      pageNumberFormat: 'full' as const,
      style: 'standard' as const,
    },
  },
  
  // Clean/professional look
  professional: {
    header: {
      showNameField: true,
      showDateField: true,
      showScoreField: false,
      style: 'compact' as const,
    },
    footer: {
      showAttribution: false,
      showPageNumbers: true,
      pageNumberFormat: 'simple' as const,
      style: 'minimal' as const,
    },
  },
} as const;

export type PresetName = keyof typeof presets;
